# Generated by Django 5.2.4 on 2025-08-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_comment_options_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
